# Generated by Django 2.0 on 2017-12-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('dep_id', models.IntegerField()),
                ('verified', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('intro', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('weixin_open_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('work_type_id', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
            options={
                'db_table': 'Members',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('work_type_id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'WorkType',
            },
        ),
        migrations.AddField(
            model_name='members',
            name='work_type_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkType'),
        ),
    ]
